import { NextResponse } from "next/server";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

export async function POST(request: Request) {
  try {
    const body = await request.json();

    const {
      url,
      research,
      sourceType,
      contentSize,
      title,
    } = body;

    if (!research) {
      return NextResponse.json(
        {
          success: false,
          error: "Research content is required",
        },
        { status: 400 }
      );
    }

    const pdfDoc = await PDFDocument.create();

    const font = await pdfDoc.embedFont(
      StandardFonts.Helvetica
    );

    const boldFont = await pdfDoc.embedFont(
      StandardFonts.HelveticaBold
    );

    const pageWidth = 595;
    const pageHeight = 842;
    const margin = 50;

    let page = pdfDoc.addPage([
      pageWidth,
      pageHeight,
    ]);

    let y = pageHeight - 60;

    const maxWidth = pageWidth - margin * 2;

    const addNewPage = () => {
      page = pdfDoc.addPage([
        pageWidth,
        pageHeight,
      ]);

      y = pageHeight - 60;
    };

    const wrapText = (
      text: string,
      fontSize: number,
      selectedFont: typeof font
    ) => {
      const words = text.split(" ");
      const lines: string[] = [];

      let currentLine = "";

      for (const word of words) {
        const testLine = currentLine
          ? `${currentLine} ${word}`
          : word;

        const width =
          selectedFont.widthOfTextAtSize(
            testLine,
            fontSize
          );

        if (width > maxWidth) {
          if (currentLine) {
            lines.push(currentLine);
          }

          currentLine = word;
        } else {
          currentLine = testLine;
        }
      }

      if (currentLine) {
        lines.push(currentLine);
      }

      return lines;
    };

    const addText = (
      text: string,
      fontSize = 12,
      isBold = false
    ) => {
      const selectedFont = isBold
        ? boldFont
        : font;

      const pdfText = text
        .replace(/[\u2018\u2019]/g, "'")
        .replace(/[\u201C\u201D]/g, '"')
        .replace(/[\u2013\u2014]/g, "-")
        .replace(/[^\x20-\x7E]/g, "");

      const lines = wrapText(
        pdfText,
        fontSize,
        selectedFont
      );

      for (const line of lines) {
        if (y < 60) {
          addNewPage();
        }

        page.drawText(line, {
          x: margin,
          y,
          size: fontSize,
          font: selectedFont,
          color: rgb(0.1, 0.1, 0.15),
        });

        y -= fontSize + 7;
      }
    };

    // TITLE

    addText(
      title || "URL Research Report",
      24,
      true
    );

    y -= 15;

    // SOURCE INFORMATION

    addText(
      "SOURCE INFORMATION",
      16,
      true
    );

    y -= 8;

    addText(
      `URL: ${url || "Not available"}`,
      11
    );

    addText(
      `Source Type: ${
        sourceType || "Website"
      }`,
      11
    );

    addText(
      `Content Size: ${
        contentSize || "Not available"
      }`,
      11
    );

    y -= 15;

    // RESEARCH REPORT

    addText(
      "RESEARCH REPORT",
      16,
      true
    );

    y -= 10;

    const researchLines =
      research.split("\n");

    for (const line of researchLines) {
      const trimmedLine = line.trim();

      if (!trimmedLine) {
        y -= 8;
        continue;
      }

      const isHeading =
        trimmedLine === "SUMMARY:" ||
        trimmedLine === "KEY INSIGHTS:" ||
        trimmedLine === "ACTION ITEMS:" ||
        trimmedLine === "VERIFICATION:";

      addText(
        trimmedLine,
        isHeading ? 14 : 11,
        isHeading
      );
    }

    y -= 20;

    addText(
      "Generated by URL Research Agent",
      10
    );

    const pdfBytes = await pdfDoc.save();

    return new NextResponse(
      Buffer.from(pdfBytes),
      {
        headers: {
          "Content-Type":
            "application/pdf",

          "Content-Disposition":
            'attachment; filename="research-report.pdf"',
        },
      }
    );
  } catch (error) {
    console.error(
      "PDF generation error:",
      error
    );

    return NextResponse.json(
      {
        success: false,
        error: "Failed to generate PDF",
      },
      { status: 500 }
    );
  }
}